import type { SeedInput, WavePlan } from './seedSchema'
import { joinLines } from './helpers'
import {
  sectionAgentRoles,
  sectionClaudeAdapter,
  sectionCodexAdapter,
  sectionDefinitionOfDone,
  sectionGlobalConstraints,
  sectionNinePhaseOctopus,
  sectionObjective,
  sectionOperatingPrinciple,
  sectionOsAdapter,
  sectionTargetRuntime,
  sectionWavePlan,
} from './generateSeedSections'

/** Build the full SEED.md. Contains exactly 11 top-level `##` sections. */
export function generateSeed(input: SeedInput, plan: WavePlan): string {
  return joinLines([
    `# SpecSeed: ${input.projectName}`,
    '',
    '> Master orchestration seed. Generated by SpecSeed.io.',
    '',
    sectionObjective(input),
    sectionOperatingPrinciple(input),
    sectionTargetRuntime(input),
    sectionGlobalConstraints(input),
    sectionNinePhaseOctopus(plan),
    sectionAgentRoles(input, plan),
    sectionWavePlan(plan),
    sectionClaudeAdapter(input),
    sectionCodexAdapter(input),
    sectionOsAdapter(input),
    sectionDefinitionOfDone(input),
    '---',
    '',
    '*Generated by SpecSeed.io — deterministic template output.*',
  ])
}
